[project]
site_url = "https://www.example.com/"
site_name = "Documentation"
site_description = "3D cadastres system"
site_author = "Surydevx"

copyright = "Copyright &copy; 2026 Surydevx"

repo_url = "https://github.com/Surydevx/3d-ulpin"
repo_name = "Surydevx/3d-ulpin"
edit_uri = "edit/main/docs/"

nav = [
  { "Get started" = "index.md" },
  { "How Things works ?" = "architecture.md" },
  { "API Reference" = "api-reference.md"},
  { "Frontend Integration" = "frontend-integration.md"},
  { "Wanna contribute?" = "development.md" },
]

# MathJax for rendering LaTeX equations
extra_javascript = [
  "https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js"
]

[project.theme]
language = "en"
features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

[project.theme.icon]
logo = "lucide/hexagon"

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"

# Light Mode
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/moon"
toggle.name = "Switch to dark mode"

# Dark Mode
[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/sun"
toggle.name = "Switch to light mode"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/Surydevx/3D-ulpin"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/suryansh-sharma-4857a2379/"

[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://x.com/Suryanshxx"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc.permalink = true
pymdownx.arithmatex.generic = true
pymdownx.betterem = {}
pymdownx.caret = {}
pymdownx.details = {}
pymdownx.emoji.emoji_generator = "zensical.extensions.emoji.to_svg"
pymdownx.emoji.emoji_index = "zensical.extensions.emoji.twemoji"
pymdownx.highlight.anchor_linenums = true
pymdownx.highlight.line_spans = "__span"
pymdownx.highlight.pygments_lang_class = true
pymdownx.inlinehilite = {}
pymdownx.keys = {}
pymdownx.magiclink = {}
pymdownx.mark = {}
pymdownx.smartsymbols = {}
pymdownx.superfences.custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
pymdownx.tabbed.alternate_style = true
pymdownx.tabbed.combine_header_slug = true
pymdownx.tasklist.custom_checkbox = true
pymdownx.tilde = {}